Add util to post json-doc diff to github comment
herbstluftwm/herbstluftwm pull request #1023
Opened 2020-11-01 14:12 UTC by t-wissmann

The script `ci/diff-json-doc.py` creates a diff of the output of the
gendoc.py script, and optionally posts this diff as a comment in a PR
discussion. Hence, we directly see how a PR affects the object system.

We should consider adding this to the travis-ci. I found the article
https://damien.pobel.fr/post/github-api-from-travisci/ very helpful
while writing the diff-json-doc.py script.

2020-11-01 20:18 UTC, blarz requested changes

2020-11-01 20:18 UTC, blarz commented on ci/diff-json-doc.py
> +        run a git commit in the git repository in the dir git_tmp.dir
git command?

2020-11-01 20:18 UTC, blarz commented on ci/diff-json-doc.py
> +        # print(comment_txt)
Debug leftover?

2020-11-02 07:46 UTC, t-wissmann commented
I've fixed the two comments, thanks!

2020-11-02 07:51 UTC, blarz approved these changes

2020-11-02 08:27 UTC, merged