Make index attribute of tags writable
herbstluftwm/herbstluftwm pull request #1025
Opened 2020-11-01 19:37 UTC by t-wissmann

This requires the respective array operations in the IndexingObject and
also it requires that the EWMH properties are updated accordingly.
While writing test cases for that, I noticed that the EWMH properties
are not updated properly when a tag is removed (this changes the index
of the clients on later tags).

The wiring of the signals now solves both issues.

2020-11-01 20:30 UTC, blarz requested changes

2020-11-01 20:30 UTC, blarz commented on src/indexingobject.h
> +        printf("fixing indices\n");
Debug leftover?

2020-11-01 20:30 UTC, blarz commented on tests/test_ewmh.py
> +    # move the tag3 to the begin of the list
beginning

2020-11-01 20:30 UTC, blarz commented on tests/test_ewmh.py
> +    # so the index of the tag of the client increased by one
decreased?

2020-11-02 07:42 UTC, t-wissmann commented on src/indexingobject.h
> +        printf("fixing indices\n");
Oh right, thanks!

2020-11-02 07:44 UTC, t-wissmann commented
Thanks, I've also fixed the two comments :)

2020-11-02 08:34 UTC, blarz commented
While playing around with this change I noticed that default panel.sh plays nicely with this, but I am using xfce4-panel and it seems to be dragging behind somehow:

I am on a tag with just one terminal, in this terminal I change the index of that tag. In the "workspace view" of xfce4-panel and in the list of windows for that workspace I still see that terminal listed under the old index.

Is there maybe something else that needs to get updated or set to "dirty"?

2020-11-02 08:55 UTC, t-wissmann commented
Hm there are still multiple bugs, that I can reproduce. I'm on it now.

2020-11-02 09:40 UTC, t-wissmann commented
There were two issues:
  - I forgot to update `_NET_CURRENT_DESKTOP` (index of the focused tag)
  - Regarding your issue: Originally, I tried to automatically correct it if the user supplies an index that is too large. However, this implied that I had to do thiese double `index != new_index` checks and in the end I know require that the index supplied by the user is in the interval [0, tag_count)

I've added test cases for both issues

2020-11-02 21:47 UTC, blarz approved these changes
Looks good to me!

2020-11-02 21:47 UTC, merged