Move Input/Output to new commandio module
herbstluftwm/herbstluftwm pull request #1127
Opened 2021-01-08 15:41 UTC by t-wissmann

The types module should provide the core type definitions and this has
nothing to do with the types Input and Output which are used in the
interface of commands.

2021-01-09 12:04 UTC, blarz requested changes
In some places types.h include could probably be removed. Not sure why IWYU doesn't complain

2021-01-09 12:04 UTC, blarz commented on src/utils.h
>  #include "types.h"
Is this still needed?

2021-01-09 12:04 UTC, blarz commented on src/settings.h
>  #include "types.h"
Is this still needed?

2021-01-09 21:10 UTC, t-wissmann commented
I think you're right! I've removed both includes and resolved the merge conflicts.

2021-01-10 11:34 UTC, blarz commented on src/settings.h
>  #include "types.h"
Thanks!

2021-01-10 11:35 UTC, blarz approved these changes

2021-01-10 11:56 UTC, merged