In-source doc for monitors
herbstluftwm/herbstluftwm pull request #1130
Opened 2021-01-08 16:34 UTC by t-wissmann

This transfers the docs on Monitor and MonitorManager from the man page
to the source code.

2021-01-09 12:15 UTC, blarz requested changes

2021-01-09 12:15 UTC, blarz commented on src/monitor.cpp
> +           "(given in number of pixels) is never occuped by tiled clients.");
occupied?

2021-01-09 21:29 UTC, t-wissmann commented on src/monitor.cpp
> +           "(given in number of pixels) is never occuped by tiled clients.");
Fixed, thanks!

2021-01-10 11:38 UTC, blarz approved these changes

2021-01-10 12:44 UTC, merged