Support error output channel internally
herbstluftwm/herbstluftwm pull request #1278
Opened 2021-04-10 13:56 UTC by t-wissmann

In the command system, the 'Output' parameter now also carries an error
channel and the command name (in addition to the standard output
channel). This is accomplished with a new class OutputChannels in
commandio.h (and Output = OutputChannels&).

So far, this only affects the command system, but not the IPC interface,
which thus simply concatenates the two output channels in the reply to
'herbstclient'.

Thus, we can now print error messages to this dedicated channel and have
the error message prefixed with the command name automatically. Most of
the diff consists of migrating the error message printing to the new
perror(), which does the prefixing.

As a bonus, CallOrComplete does not need the command name anymore.

Also, HlwmCommon::callCommand() was only used in XMainLoop, so I have
used it there.

2021-04-13 19:57 UTC, blarz requested changes
Two minor findings, other than that, this looks good and grep shows me that you spotted all .command() occurrences

2021-04-13 19:57 UTC, blarz commented on src/commandio.h
>      //! the name of the command that is called.
Can be removed now?

2021-04-13 19:57 UTC, blarz commented on src/metacommands.cpp
> +    // the ipc-protocoll supports it.
protocol

2021-04-15 07:25 UTC, t-wissmann commented on src/commandio.h
>      //! the name of the command that is called.
Indeed, thanks!

2021-04-15 07:25 UTC, t-wissmann commented on src/metacommands.cpp
> +    // the ipc-protocoll supports it.
Fixed, thanks!

2021-04-15 07:27 UTC, t-wissmann commented
> Two minor findings, other than that, this looks good and grep shows me that you spotted all .command() occurrences

Thanks, I've fixed them. Regarding `command()`, I had temporarily renamed `Input::command()` and `CallOrCommand::command()` and went through all compile errors :)

2021-04-15 10:59 UTC, blarz commented on src/commandio.h
>      //! the name of the command that is called.
Thanks!

2021-04-15 11:00 UTC, blarz approved these changes
Looks good to me!

2021-04-15 11:00 UTC, merged