Error channel in progress
herbstluftwm/herbstluftwm pull request #1285
Opened 2021-04-18 13:30 UTC by t-wissmann

This extends the ipc protocol by an error channel that is printed to
'stderr' by herbstclient.

2021-04-19 20:01 UTC, t-wissmann commented
I think, now it is ready :)

2021-04-20 06:17 UTC, blarz requested changes
Minor findings

2021-04-20 06:17 UTC, blarz commented on tests/test_rules.py
>      # message appears on stdout
stderr?

2021-04-20 06:17 UTC, blarz commented on tests/test_herbstclient.py
> +    """A simply re-implementation of the ipc server
simple

2021-04-20 06:17 UTC, blarz commented on src/ipc-protocol.h
> +/** if this (integer) atom present and non-empty on the hook window,
"is" missing?

2021-04-20 06:17 UTC, blarz commented on ipc-client/ipc-client.h
> + * if false is returned, then none of the ret_⎄-pointers is set.
ret_⎄ strange unicode garbage?

2021-04-20 19:47 UTC, blarz commented
Not related to this change but maybe for another PR:
```
out << "error: Command \"" << args.command() << "\" not found" << endl;
```
in command.cpp could also be moved to stderr somehow?

2021-04-21 09:02 UTC, t-wissmann commented
Thanks for looking through the long diff :-)
I've fixed all the points you mentioned and created a new PR for the "command not found" error: #1286

2021-04-21 12:20 UTC, blarz approved these changes
Looks good to me, played around with it locally, too

2021-04-21 12:21 UTC, merged