Update floating geometry if size hints change
herbstluftwm/herbstluftwm pull request #1324
Opened 2021-05-22 14:28 UTC by t-wissmann

If the size hints of a client change, then its floating geometry must be
updated. Also, this must happen even if the client is not floated at the
moment. To accomplish the latter, the applysizehints() function is
extended by an optional `force` parameter. The new test case verifies
both the floating and non-floating case.

This fixes #1322.

2021-05-23 17:46 UTC, blarz requested changes
Just some remarks on docstrings, other than that, it looks good to me.
(NEWS might need a merge conflict resolve)

2021-05-23 17:46 UTC, blarz commented on src/client.cpp
> + * @param width
w

2021-05-23 17:46 UTC, blarz commented on src/client.cpp
> + * @param height
h

2021-05-23 17:46 UTC, blarz commented on src/client.cpp
> + * @param If set, always apply the size hints. If not set, only
@param force

2021-05-23 17:47 UTC, blarz commented on src/client.cpp
> + * @param width
Oh, we don't actually state the name of the parameter here again, so "width" is the description of the parameter 'w'. Resolving this.

2021-05-23 17:48 UTC, blarz commented on src/client.cpp
> + * @param height
Nevermind

2021-05-23 17:48 UTC, blarz commented on src/client.cpp
> + * @param If set, always apply the size hints. If not set, only
Nevermind

2021-05-23 17:58 UTC, t-wissmann commented
Regarding restating the parameter name after `@param`: I'm not entirely sure how doxygen defines it. But I'd guess that for avoiding redundancy, one does not need to restate it because the doxygen generator can mention the parameter name next its description automatically.

2021-05-23 18:01 UTC, t-wissmann commented
Oh no, it seems I am wrong and one must restate the parameter name. Running `doxygen` yields e.g.:
![image](https://user-images.githubusercontent.com/9048813/119271388-983c2600-bc01-11eb-8938-718d31288a39.png)

2021-05-23 18:11 UTC, t-wissmann commented
I've fixed it for the `applysizehints()` function:
![image](https://user-images.githubusercontent.com/9048813/119271734-1220df00-bc03-11eb-982f-666fd82c9af0.png)

2021-05-24 09:12 UTC, blarz commented
> I've fixed it for the `applysizehints()` function:
> ![image](https://user-images.githubusercontent.com/9048813/119271734-1220df00-bc03-11eb-982f-666fd82c9af0.png)

Thanks for looking into that and fixing it right away! :)

2021-05-24 09:12 UTC, blarz approved these changes

2021-05-24 09:13 UTC, merged