Add an autostart object
herbstluftwm/herbstluftwm pull request #1332
Opened 2021-06-03 06:26 UTC by t-wissmann

This adds an autostart object which allows modifying the custom
autostart path at run time and also helps querying information about the
last invoked autostart run (pid, status, running).

This closes #762.

2021-06-03 06:28 UTC, t-wissmann commented
Maybe `last_status` can be simplified to `status` or `exit_status`.

2021-06-05 09:40 UTC, blarz requested changes
Some small typos, otherwise looks good!

Also: there are some autostart related tests in test_herbstluftwm.py, maybe they can be removed or update?

2021-06-05 09:40 UTC, blarz commented on src/autostart.cpp
> +                "the process id of the last autostart invokation. "
invocation

2021-06-05 09:40 UTC, blarz commented on src/main.cpp
> +    // receive anything on on stopped children (SA_NOCLDSTOP)
on on

2021-06-05 09:41 UTC, blarz commented
> Some small typos, otherwise looks good!
> 
> Also: there are some autostart related tests in test_herbstluftwm.py, maybe they can be removed or update?

At least the `# TODO: verify the path as soon as we have an autostart object` comment seems like something that could be done (maybe in a different PR?)

2021-06-06 06:31 UTC, t-wissmann commented
I've fixed the typos and moved the test cases to `test_autostart.py`. The comment in `test_autostart_path` however requires another attribute that does not exist yet, so I think this should be done in separate PR.

2021-06-06 08:03 UTC, blarz commented
> I've fixed the typos and moved the test cases to `test_autostart.py`. The comment in `test_autostart_path` however requires another attribute that does not exist yet, so I think this should be done in separate PR.

Thanks for the fixes. And makes sense :)

2021-06-06 08:04 UTC, blarz approved these changes

2021-06-06 08:04 UTC, merged