Resize frames in both dimensions
herbstluftwm/herbstluftwm pull request #1348
Opened 2021-07-28 18:44 UTC by t-wissmann

This implements a feature which was already indicated by the cursor shape:
resizing frames in both x and y direction. For this, it was necessary to
entirely change the drag handler for resizing frames.

As a little bonus, the special cursor shape persists during the drag.

The new test case essentially checks that resizing in both dimensions
work as expected. The existing testcase for 1-dimensional resize
could be simplified a lot using new attributes and the convenience
functions in the python bindings.

2021-08-02 21:09 UTC, blarz requested changes
Just two minor things, other than that it looks good me!

2021-08-02 21:09 UTC, blarz commented on src/decoration.cpp
> + * @return
Add a description of the return value?

2021-08-06 11:20 UTC, t-wissmann commented
Thanks! I've fixed the two instances.

2021-08-10 16:59 UTC, blarz commented on src/decoration.cpp
> + * @return
Thanks!

2021-08-10 16:59 UTC, blarz commented on src/decoration.cpp
> + * @brief Find the most apropriate ResizeAction given the current
Thanks!

2021-08-10 16:59 UTC, blarz approved these changes

2021-08-10 17:23 UTC, merged