Extend 'foreach' with a --filter-name=REGEX flag
herbstluftwm/herbstluftwm pull request #1387
Opened 2021-12-01 22:37 UTC by t-wissmann

This migrates the 'foreach' command to the ArgParse/CallOrComplete system which
makes it easy to add command line flags to the invocation syntax.
For this, the ArgParse class had to be extended slightly such that it
also support additional arguments after the positional arguments and
flags. In the 'foreach' example, those additional arguments specify the
nested command, i.e. the 'loop body'.

2021-12-02 10:11 UTC, t-wissmann commented
The CI is fine. The only issue here is a2x, that randomly breaks (this happend already in previous PRs):
```
a2x: ERROR: "xsltproc"  --stringparam callout.graphics 0 --stringparam
navig.graphics 0 --stringparam admon.textlabel 1 --stringparam admon.graphics 0
"/etc/asciidoc/docbook-xsl/manpage.xsl"
"/home/runner/work/herbstluftwm/herbstluftwm/build-1017/doc/herbstclient.xml"
returned non-zero exit status 6
```

2021-12-03 19:44 UTC, blarz requested changes
Just a small doc string issue, otherwise looks!

2021-12-04 08:15 UTC, t-wissmann commented on src/argparse.cpp
> + * yet parsed tokens after the
oups. after the " positional arguments and flags." :-)

2021-12-04 09:53 UTC, blarz commented on src/argparse.cpp
> + * yet parsed tokens after the
Thanks :)

2021-12-04 09:53 UTC, blarz approved these changes
Looks good to me :)

2021-12-04 09:53 UTC, merged