New constant string format specifier for sprintf
herbstluftwm/herbstluftwm pull request #994
Opened 2020-08-17 13:38 UTC by t-wissmann

This introduces a new format specifier '%c' in the sprintf format
strings. Of course it never makes sense to manually write something like

    hc sprintf S '%c.name' 'tags.0'

but it makes sense in combination with the other commands that replace
certain identfiers in commands, especiall in comination with the foreach
command.

This change required an update in the completion code for the 'sprintf'
command, and while at it, I fixed a minor bug in the completion. The bug
was that completing the command

   hc sprintf S '%s'

erroneously yielded S.

2020-08-18 19:29 UTC, blarz commented
Fixed some typos in the PR description.

2020-08-18 19:36 UTC, blarz requested changes

2020-08-18 19:36 UTC, blarz commented on src/rootcommands.cpp
> +        } else if (blob.data_ == "c"){
Style: Add a space between ) and {

2020-08-18 19:36 UTC, blarz commented on src/rootcommands.cpp
> +        int	indexOfNextArgument = 2;
Double whitespace

2020-08-18 21:34 UTC, t-wissmann commented
I've fixed both whitespace issues (the 'double' whitespace was a tab; I don't know how qtcreator was able to sneak that in)

2020-08-19 07:24 UTC, blarz submitted a review, later dismissed
Nice! Looking forward to see what the users will do with this :D

2020-08-19 07:57 UTC, t-wissmann commented
I've pushed a new commit resolving the merge conflicts in `doc/herbstluftwm.txt` that arised from the merge of the foreach-PR.

As soon as this is merged, I can answer a few open issues/feature requests :-) (closing all clients is one of them)

2020-08-19 08:03 UTC, blarz approved these changes

2020-08-19 08:13 UTC, merged